### ISSUE TITLE
1400 colors slow

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_palette#2]
Лучше выкинуть палитру, последнюю, она открывается 4-11 секунд

**Comment by kvichans** [comment]
1. Она никак не мешает работать с остальными палитрами.
2. Есть идеи _оптимизации_

**Comment by kvichans** [comment]
Увы. Выяснил, что любые оптимизации на моем слое - это как "слону дробина". 
Из 5 сек задержки, которые я вижу у себя, на мой слой приходится менее 0.1 сек.

**Comment by kvichans** [comment]
Добавлю фильтр, чтобы можно было отображались только часть палитр.
