### ISSUE TITLE
New call

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_palette#4]
нужен формат вызова, для i18n.
Пример- dlg.....(color, s_title, s_cancel, s_no_color, s_colors, s_opt_mark, s_opt_near)

**Comment by kvichans** [comment]
Предложенный вариант локализации слишком куцый. Кроме подписей на кнопках отображаются еще много других текстов.
В реализацию заложена технология перевода **всего** интерфейса на другие языки через gettext. Технология проверена на FindInFile и ExtTools.

Предлагаю не делать _костыль_

**Comment by Alexey-T** [comment]
Давайте лучше костыль (а то длг не переведет ~никто)

**Comment by kvichans** [comment]
Все равно, нужно делать более технологично.
Например, так
`dlg_color_palette(s_title, n_color=None, s_palette_type=None, i18n={})`  
Через `i18n` можно передать новые подписи, используя старые, как ключи: 
```
i18n['Cancel']='Отмена'
i18n['M&ark named']='Есть &имена'
i18n['N&earby']='Бли&зкие'
i18n['&No color']='Без &цвета'
```
Тогда я смогу встроить это в существующую технологию перевода.

**Comment by Alexey-T** [comment]
Нет, не старые подписи как ключи а просто ид как ключи, типа "canc", "noclr"
Про старые подписи Куд не должен знать

**Comment by kvichans** [comment]
Ладно, пусть будут искусственные ключи
```
i18n['cancel']='Отмена'
i18n['named']='Есть &имена'
i18n['nearby']='Бли&зкие'
i18n['nocolor']='Без &цвета'
```
След. версия будет их ждать

**Comment by Alexey-T** [comment]
Для др языков кнопы подлиннее , плс

**Comment by kvichans** [comment]
ok
