### ISSUE TITLE
Op Nearby

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_palette#5]
что делает опция? дам нормальный перевод хинта.

**Comment by kvichans** [comment]
Ищет ближайший именованный цвет.

Для справки: сейчас используется L0-RGB-метрика, то есть 
`|c1, c2| = abs(c1.R-c2.R)+abs(c1.G-c2.G)+abs(c1.B-c2.B)`

**Comment by Alexey-T** [comment]
что значит "ищет цвет"- как это относится к тому что появляются . и ..

**Comment by kvichans** [comment]
При поиске вычисляется расстояние до ближайшего цвета с известным именем d=|c_curr, c_named|. По нему можно судить о степени доверия к найденному имени.
При d<=3 можно доверять, ставится "!"
При 3<d<=9 доверять еще можно, ставится "."
При 9<d велика вероятность обознаться, ставится ".."
Формула для расстояния может изменится и числа в проверках _условные_.

**Comment by Alexey-T** [comment]
что за цвет- c_curr? Который выбран при вызове дл?

**Comment by Alexey-T** [comment]
Можно дать такой хинт
-Show additional marks, for colors which are "near" any named color. Mark char is: . if distance very low, .. if distance middle.

**Comment by kvichans** [comment]
В вашей подсказке упущен существенный смысл. 
Галка [x]Nearby не включает отображение "."/"..", а назначает имена, которые будут появляться в hint, и маркеры "."/".." показывают насколько это действие удачное.

Мой новый вариант для подсказки
```
Assign nearby names. Add more marks to show what distance is. Marks are:'
"!" if distance is very low, '
"." if distance is small, '
".." all others.
```

**Comment by Alexey-T** [comment]
~~~
Assign names to some colors, which are "near" named colors. Marks show distance to these near colors:
"!" if distance is very low,
"." if distance is small,
".." all others.
~~~

**Comment by kvichans** [comment]
ok
